services:
  nextjs-app:
    container_name: menu-app
    restart: always
    ports:
      - "3002:3000"
    build:
      context: ./
      dockerfile: ./Dockerfile
      # args:
      #   - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      #   - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
    image: menu-app:0.1
    pull_policy: always
    env_file:
      - stack.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      
