services:
  nextjs-app:
    container_name: menu-app
    restart: always
    ports:
      - "3002:3002"
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    image: menu-app:0.1
    pull_policy: always
    # env_file:
    #   - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      
